
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/bbox_hw_statistics.ipynb

#================================================
from matplotlib import patches


#================================================
def draw_rect(ax, x,y,w,h, color='white',lw=2):
    patch = ax.add_patch(patches.Rectangle((x,y), w, h, fill=False, edgecolor=color, lw=lw))
    return patch
